# Generated by Django 3.2 on 2022-02-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_teams_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
